name: CI Pipeline

# 워크플로를 실행할 이벤트 정의
on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

  pull_request:
    branches:
      - main  # main 브랜치로 PR이 생성될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 레포지토리에서 코드를 가져옴
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Node.js 환경 설정
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    # 3. 의존성 설치
    - name: Install dependencies
      run: npm install

    # 4. Docker 이미지 빌드
    - name: Build Docker image
      run: docker build -t your-dockerhub-dlvndgur01/your-image-name .

    # 5. Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Docker 이미지 푸시
    - name: Push Docker image
      run: docker push your-dockerhub-dlvndgur01/your-image-name:latest
